/**
 * Cross-Reference Validator — K-7 / S-8
 *
 * @req SC-K7-001 — broken markdown links between canonical docs are reported
 * @req SC-K7-002 — broken intra-doc anchors are reported
 * @req SC-K7-003 — external URLs (http/https) are NOT checked
 * @req SC-K7-004 — code-fenced examples don't trigger false positives
 * @req SC-K7-005 — slugifyHeading matches GitHub's GFM rules for common cases
 */
import { describe, it, afterEach } from 'node:test';
import { strict as assert } from 'node:assert';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import {
  slugifyHeading,
  extractHeadings,
  extractRefs,
  validateCrossReferences,
} from '../cli/validators/cross-reference.mjs';

function makeRepo(files) {
  const dir = mkdtempSync(join(tmpdir(), 'docguard-xref-'));
  for (const [rel, content] of Object.entries(files)) {
    const full = join(dir, rel);
    mkdirSync(join(full, '..'), { recursive: true });
    writeFileSync(full, content);
  }
  return dir;
}

describe('slugifyHeading — GFM-compatible slugger', () => {
  it('lowercases and dasherizes simple headings', () => {
    assert.equal(slugifyHeading('## Quick Start'), 'quick-start');
    assert.equal(slugifyHeading('### API Reference'), 'api-reference');
  });

  it('strips common punctuation', () => {
    assert.equal(slugifyHeading('What is it?'), 'what-is-it');
    assert.equal(slugifyHeading('Section 3.2: Components'), 'section-32-components');
  });

  it('collapses runs of whitespace to a single dash', () => {
    // Pragmatic compromise: we collapse \s+ to one dash rather than
    // tr-replacing each space char. Most real-world headings have single
    // spaces between words, and this avoids weird false positives like
    // `multi---space---heading` from accidental whitespace. The `--` case
    // is still preserved when a stripped punctuation character was BETWEEN
    // two dash-producing spaces (see next test).
    assert.equal(slugifyHeading('Multi   space   heading'), 'multi-space-heading');
  });

  it('keeps double dashes when stripped punctuation creates them', () => {
    // `Research & Academic` flow:
    //   → lowercased: 'research & academic'
    //   → \s+ to dash: 'research-&-academic'
    //   → strip non-word: 'research--academic' (the `&` between two dashes
    //     gets removed, leaving the dashes adjacent)
    assert.equal(slugifyHeading('Research & Academic'), 'research--academic');
    assert.equal(slugifyHeading('Multi-Dash--Heading'), 'multi-dash--heading');
  });

  it('handles emoji the way GitHub does (keeps the leading dash)', () => {
    // GitHub's anchor for `## 🎯 Goals` is `#-goals`, not `#goals`.
    // The leading dash comes from the position where the emoji was stripped.
    // Matching GitHub's behavior here is REQUIRED — otherwise any markdown
    // TOC generated by GitHub itself would false-positive as a broken link.
    assert.equal(slugifyHeading('## 🎯 Goals'), '-goals');
    assert.equal(slugifyHeading('## ⚡ Quick Start'), '-quick-start');
  });

  it('matches GitHub: keeps leading dash for emoji-prefixed headings', () => {
    // Regression guard against accidentally re-introducing `.replace(/^-|-$/g, '')`.
    assert.equal(slugifyHeading('### 🛡️ Validators'), '-validators');
    assert.equal(slugifyHeading('## 🎓 Research & Academic Credits'), '-research--academic-credits');
  });
});

describe('extractHeadings', () => {
  it('returns all ATX-style headings with computed anchors', () => {
    const md = '# Title\n## Sub One\n### Deep One\nbody\n## Sub Two';
    const h = extractHeadings(md);
    assert.equal(h.length, 4);
    assert.deepEqual(h.map(x => x.anchor), ['title', 'sub-one', 'deep-one', 'sub-two']);
  });

  it('skips headings inside fenced code blocks', () => {
    const md = '# Real Heading\n```\n## Fake Heading In Code\n```\n## Another Real';
    const h = extractHeadings(md);
    assert.equal(h.length, 2);
    assert.deepEqual(h.map(x => x.anchor), ['real-heading', 'another-real']);
  });
});

describe('extractRefs', () => {
  it('extracts simple markdown links', () => {
    const md = 'See [Architecture](./ARCH.md) for details.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 1);
    assert.equal(refs[0].file, './ARCH.md');
    assert.equal(refs[0].anchor, null);
  });

  it('extracts links with anchors', () => {
    const md = 'See [§3.2](./ARCH.md#components) for details.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs[0].file, './ARCH.md');
    assert.equal(refs[0].anchor, 'components');
  });

  it('extracts intra-doc anchor refs', () => {
    const md = 'See [the next section](#second-half).';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs[0].file, null);
    assert.equal(refs[0].anchor, 'second-half');
  });

  it('SKIPS external URLs', () => {
    const md = 'See [docs](https://example.com/foo) and [code](http://example.org#x).';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 0, 'external URLs must not be reported');
  });

  it('SKIPS mailto: links', () => {
    const md = 'Contact [us](mailto:foo@bar.com).';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 0);
  });

  it('SKIPS code-fenced examples', () => {
    const md = '```\n[fake link](./not-real.md)\n```\nBut [this](./real.md) counts.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 1);
    assert.equal(refs[0].file, './real.md');
  });

  it('SKIPS inline `code` text', () => {
    const md = 'The syntax `[label](./not-real.md)` is markdown. But [this](./real.md) is a real link.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 1);
    assert.equal(refs[0].file, './real.md');
  });
});

describe('validateCrossReferences — end-to-end', () => {
  let dir;
  afterEach(() => { if (dir) rmSync(dir, { recursive: true, force: true }); });

  it('reports broken file links (target file missing)', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [Data Model](./DATA-MODEL.md) for entities.\n',
      // Intentionally NO DATA-MODEL.md
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.length >= 1, 'broken link should produce a warning');
    assert.ok(r.warnings.some(w => w.includes('DATA-MODEL.md') && w.includes('not found')),
      'warning should name the missing target');
  });

  it('reports broken intra-doc anchors', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [components](#components) below.\n## Services\nstub\n',
      // Heading "Components" missing; "Services" exists.
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('#components') && w.includes('same doc')),
      'broken intra-doc anchor must be reported');
  });

  it('reports broken cross-file anchors', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [§3](./DATA-MODEL.md#missing-section).\n',
      'docs-canonical/DATA-MODEL.md':
        '# Data Model\n## Users\n## Orders\n',
      // No "missing-section" heading
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('#missing-section') && w.includes('DATA-MODEL.md')),
      'broken cross-file anchor should name the doc + anchor');
  });

  it('does NOT report valid links', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [§3](./DATA-MODEL.md#users) and [intra](#services).\n## Services\nstub\n',
      'docs-canonical/DATA-MODEL.md':
        '# Data Model\n## Users\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.length, 0, `expected no warnings, got: ${r.warnings.join(', ')}`);
    assert.equal(r.passed, 2);
    assert.equal(r.total, 2);
  });

  it('does NOT touch external URLs', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nLinks: [GitHub](https://github.com/x/y) and [npm](https://npmjs.com).',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.total, 0, 'external URLs should not be counted as refs');
  });

  it('is N/A when no canonical docs exist', () => {
    dir = makeRepo({ 'package.json': '{}' });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.applicable, false);
  });

  it('skips links to non-markdown files (images, code samples, etc.)', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee ![diagram](./diagram.png) and [config](./settings.json).\n',
      // PNG/JSON files don't exist — but we shouldn't warn about them.
    });
    const r = validateCrossReferences(dir, {});
    // 2 refs counted, both passed (skipped non-md target = pass)
    assert.equal(r.warnings.length, 0);
  });
});
