/**
 * Cross-Reference Validator — K-7 / S-8
 *
 * @req SC-K7-001 — broken markdown links between canonical docs are reported
 * @req SC-K7-002 — broken intra-doc anchors are reported
 * @req SC-K7-003 — external URLs (http/https) are NOT checked
 * @req SC-K7-004 — code-fenced examples don't trigger false positives
 * @req SC-K7-005 — slugifyHeading matches GitHub's GFM rules for common cases
 */
import { describe, it, afterEach } from 'node:test';
import { strict as assert } from 'node:assert';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import {
  slugifyHeading,
  extractHeadings,
  extractRefs,
  validateCrossReferences,
  suggestAnchor,
} from '../cli/validators/cross-reference.mjs';

function makeRepo(files) {
  const dir = mkdtempSync(join(tmpdir(), 'docguard-xref-'));
  for (const [rel, content] of Object.entries(files)) {
    const full = join(dir, rel);
    mkdirSync(join(full, '..'), { recursive: true });
    writeFileSync(full, content);
  }
  return dir;
}

describe('slugifyHeading — GFM-compatible slugger', () => {
  it('lowercases and dasherizes simple headings', () => {
    assert.equal(slugifyHeading('## Quick Start'), 'quick-start');
    assert.equal(slugifyHeading('### API Reference'), 'api-reference');
  });

  it('strips common punctuation', () => {
    assert.equal(slugifyHeading('What is it?'), 'what-is-it');
    assert.equal(slugifyHeading('Section 3.2: Components'), 'section-32-components');
  });

  it('collapses runs of whitespace to a single dash', () => {
    // Pragmatic compromise: we collapse \s+ to one dash rather than
    // tr-replacing each space char. Most real-world headings have single
    // spaces between words, and this avoids weird false positives like
    // `multi---space---heading` from accidental whitespace. The `--` case
    // is still preserved when a stripped punctuation character was BETWEEN
    // two dash-producing spaces (see next test).
    assert.equal(slugifyHeading('Multi   space   heading'), 'multi-space-heading');
  });

  it('keeps double dashes when stripped punctuation creates them', () => {
    // `Research & Academic` flow:
    //   → lowercased: 'research & academic'
    //   → \s+ to dash: 'research-&-academic'
    //   → strip non-word: 'research--academic' (the `&` between two dashes
    //     gets removed, leaving the dashes adjacent)
    assert.equal(slugifyHeading('Research & Academic'), 'research--academic');
    assert.equal(slugifyHeading('Multi-Dash--Heading'), 'multi-dash--heading');
  });

  it('handles emoji the way GitHub does (keeps the leading dash)', () => {
    // GitHub's anchor for `## 🎯 Goals` is `#-goals`, not `#goals`.
    // The leading dash comes from the position where the emoji was stripped.
    // Matching GitHub's behavior here is REQUIRED — otherwise any markdown
    // TOC generated by GitHub itself would false-positive as a broken link.
    assert.equal(slugifyHeading('## 🎯 Goals'), '-goals');
    assert.equal(slugifyHeading('## ⚡ Quick Start'), '-quick-start');
  });

  it('matches GitHub: keeps leading dash for emoji-prefixed headings', () => {
    // Regression guard against accidentally re-introducing `.replace(/^-|-$/g, '')`.
    assert.equal(slugifyHeading('### 🛡️ Validators'), '-validators');
    assert.equal(slugifyHeading('## 🎓 Research & Academic Credits'), '-research--academic-credits');
  });
});

describe('extractHeadings', () => {
  it('returns all ATX-style headings with computed anchors', () => {
    const md = '# Title\n## Sub One\n### Deep One\nbody\n## Sub Two';
    const h = extractHeadings(md);
    assert.equal(h.length, 4);
    assert.deepEqual(h.map(x => x.anchor), ['title', 'sub-one', 'deep-one', 'sub-two']);
  });

  it('skips headings inside fenced code blocks', () => {
    const md = '# Real Heading\n```\n## Fake Heading In Code\n```\n## Another Real';
    const h = extractHeadings(md);
    assert.equal(h.length, 2);
    assert.deepEqual(h.map(x => x.anchor), ['real-heading', 'another-real']);
  });
});

describe('extractRefs', () => {
  it('extracts simple markdown links', () => {
    const md = 'See [Architecture](./ARCH.md) for details.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 1);
    assert.equal(refs[0].file, './ARCH.md');
    assert.equal(refs[0].anchor, null);
  });

  it('extracts links with anchors', () => {
    const md = 'See [§3.2](./ARCH.md#components) for details.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs[0].file, './ARCH.md');
    assert.equal(refs[0].anchor, 'components');
  });

  it('extracts intra-doc anchor refs', () => {
    const md = 'See [the next section](#second-half).';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs[0].file, null);
    assert.equal(refs[0].anchor, 'second-half');
  });

  it('SKIPS external URLs', () => {
    const md = 'See [docs](https://example.com/foo) and [code](http://example.org#x).';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 0, 'external URLs must not be reported');
  });

  it('SKIPS mailto: links', () => {
    const md = 'Contact [us](mailto:foo@bar.com).';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 0);
  });

  it('SKIPS code-fenced examples', () => {
    const md = '```\n[fake link](./not-real.md)\n```\nBut [this](./real.md) counts.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 1);
    assert.equal(refs[0].file, './real.md');
  });

  it('SKIPS inline `code` text', () => {
    const md = 'The syntax `[label](./not-real.md)` is markdown. But [this](./real.md) is a real link.';
    const refs = extractRefs(md, '/tmp/x/SOURCE.md');
    assert.equal(refs.length, 1);
    assert.equal(refs[0].file, './real.md');
  });
});

describe('validateCrossReferences — end-to-end', () => {
  let dir;
  afterEach(() => { if (dir) rmSync(dir, { recursive: true, force: true }); });

  it('reports broken file links (target file missing)', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [Data Model](./DATA-MODEL.md) for entities.\n',
      // Intentionally NO DATA-MODEL.md
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.length >= 1, 'broken link should produce a warning');
    assert.ok(r.warnings.some(w => w.includes('DATA-MODEL.md') && w.includes('not found')),
      'warning should name the missing target');
  });

  it('reports broken intra-doc anchors', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [components](#components) below.\n## Services\nstub\n',
      // Heading "Components" missing; "Services" exists.
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('#components') && w.includes('same doc')),
      'broken intra-doc anchor must be reported');
  });

  it('reports broken cross-file anchors', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [§3](./DATA-MODEL.md#missing-section).\n',
      'docs-canonical/DATA-MODEL.md':
        '# Data Model\n## Users\n## Orders\n',
      // No "missing-section" heading
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('#missing-section') && w.includes('DATA-MODEL.md')),
      'broken cross-file anchor should name the doc + anchor');
  });

  it('does NOT report valid links', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [§3](./DATA-MODEL.md#users) and [intra](#services).\n## Services\nstub\n',
      'docs-canonical/DATA-MODEL.md':
        '# Data Model\n## Users\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.length, 0, `expected no warnings, got: ${r.warnings.join(', ')}`);
    assert.equal(r.passed, 2);
    assert.equal(r.total, 2);
  });

  it('does NOT touch external URLs', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nLinks: [GitHub](https://github.com/x/y) and [npm](https://npmjs.com).',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.total, 0, 'external URLs should not be counted as refs');
  });

  it('is N/A when no canonical docs exist', () => {
    dir = makeRepo({ 'package.json': '{}' });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.applicable, false);
  });

  it('S-12: suggests the closest anchor when a near-miss is detected', () => {
    // Heading renamed but the link wasn't updated — most common wu case.
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\n\nSee [setup](#athena-setup) for details.\n\n' +
        '## Athena Setup (AWS Only)\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.length >= 1, 'broken anchor should warn');
    const w = r.warnings[0];
    assert.match(w, /did you mean #athena-setup-aws-only\?/,
      `warning should include suggested slug; got: ${w}`);
  });

  it('S-12: does NOT suggest when no candidate is close enough', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\n\nSee [foo](#totally-unrelated-anchor).\n\n## Components\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.length >= 1);
    const w = r.warnings[0];
    assert.doesNotMatch(w, /did you mean/,
      'no suggestion when nothing is close enough');
  });

  it('B-6: resolves URL-encoded paths (e.g. %20 for spaces)', () => {
    // Real-world case from wu-whatsappinbox: a doc directory has a space in
    // its name ("WU Documentation"), CommonMark allows the URL-encoded form,
    // but the filesystem stores the decoded form. The validator should try
    // both.
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# Architecture\nSee [external](./../WU%20Documentation/foo.md) for the WU spec.\n',
      'WU Documentation/foo.md': '# Foo\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(
      r.warnings.every(w => !w.includes('not found')),
      `URL-encoded path should resolve via decode; got warnings: ${r.warnings.join(' | ')}`
    );
  });

  it('B-6: falls back to literal path when decode fails (% in a real path)', () => {
    // Edge: a file literally named "100%.md". The literal lookup should
    // succeed; the decode attempt would throw URIError and fall back.
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee [pct](./100%.md).\n',
      'docs-canonical/100%.md': '# 100%\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    // Either resolves correctly OR doesn't crash — both acceptable. The
    // bug we're guarding against is "throws on malformed decode".
    assert.ok(Array.isArray(r.warnings), 'should not crash on % in path');
  });

  it('skips links to non-markdown files (images, code samples, etc.)', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee ![diagram](./diagram.png) and [config](./settings.json).\n',
      // PNG/JSON files don't exist — but we shouldn't warn about them.
    });
    const r = validateCrossReferences(dir, {});
    // 2 refs counted, both passed (skipped non-md target = pass)
    assert.equal(r.warnings.length, 0);
  });

  it('strips query strings: ./DATA-MODEL.md?x=1#entities resolves to DATA-MODEL.md', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee [dm](./DATA-MODEL.md?plain=1#entities).\n',
      'docs-canonical/DATA-MODEL.md': '# DM\n## Entities\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.length, 0, JSON.stringify(r.warnings));
  });

  it('resolves CommonMark angle-bracket targets with spaces', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee [dm](<./data model.md#entities>).\n',
      'docs-canonical/data model.md': '# DM\n## Entities\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.length, 0, JSON.stringify(r.warnings));
  });
});

describe('validateCrossReferences — wikilinks', () => {
  let dir;
  afterEach(() => { if (dir) rmSync(dir, { recursive: true, force: true }); });

  it('flags a broken wikilink once the repo shows wikilinks-are-files evidence', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee [[DATA-MODEL]] and [[MISSING-DOC]].\n',
      'docs-canonical/DATA-MODEL.md': '# DM\nstub\n', // resolves → evidence
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('[[MISSING-DOC]]') && w.includes('not found')),
      JSON.stringify(r.warnings));
    assert.ok(!r.warnings.some(w => w.includes('[[DATA-MODEL]]')), 'resolved wikilink must pass');
  });

  it('stays SILENT when nothing resolves and no .obsidian exists (non-file [[x]] conventions)', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nMemory convention: link facts with [[some-slug]] and [[another-slug]].\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.filter(w => w.includes('wikilink')).length, 0, JSON.stringify(r.warnings));
  });

  it('.obsidian/ presence alone is evidence enough', () => {
    dir = makeRepo({
      '.obsidian/app.json': '{}',
      'docs-canonical/ARCHITECTURE.md': '# A\nSee [[MISSING-DOC]].\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('[[MISSING-DOC]]')), JSON.stringify(r.warnings));
  });

  it('validates wikilink heading anchors through the slug pipeline', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee [[DATA-MODEL#Quick Start]] and [[DATA-MODEL#Nope Nope]].\n',
      'docs-canonical/DATA-MODEL.md': '# DM\n## Quick Start\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.ok(r.warnings.some(w => w.includes('Nope Nope')), JSON.stringify(r.warnings));
    assert.ok(!r.warnings.some(w => w.includes('Quick Start') && w.includes('broken')),
      'valid heading anchor must pass');
  });

  it('supports [[Target|alias]] and ignores image embeds ![[img.png]]', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md':
        '# A\nSee [[DATA-MODEL|the data model]] and ![[missing-diagram.png]].\n',
      'docs-canonical/DATA-MODEL.md': '# DM\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.length, 0, JSON.stringify(r.warnings));
  });

  it('resolves wikilinks vault-wide by basename via doc homes (docs/)', () => {
    dir = makeRepo({
      'docs-canonical/ARCHITECTURE.md': '# A\nSee [[nested-note]].\n',
      'docs/guides/nested-note.md': '# Nested\nstub\n',
    });
    const r = validateCrossReferences(dir, {});
    assert.equal(r.warnings.filter(w => w.includes('nested-note')).length, 0, JSON.stringify(r.warnings));
  });
});
