/**
 * Feedback Command — prepare opt-in detection feedback.
 *
 * Select uncertain findings by default, or challenge active findings with
 * --code / --all. Full local records may contain private diagnostics;
 * --preview skips feedback-record writes. Persistence outcomes are explicit.
 *
 * Shared issue and search URLs contain only allowlisted finding identity,
 * tool metadata, and contribution instructions. Paths, source text, messages,
 * suggestions, and redactedContext are excluded. URLs are capped; users must
 * review and supply a synthetic reproduction before submitting an issue.
 *
 * Nothing is transmitted automatically. This command never scaffolds skills
 * or edits source files. Zero npm dependencies — pure Node.js built-ins.
 */

import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { c } from '../shared.mjs';
import { CODES } from '../findings.mjs';
import { safeWrite } from '../writers/generate-io.mjs';
import { runGuardInternal } from './guard.mjs';

const _PKG = JSON.parse(
  readFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', 'package.json'), 'utf-8')
);
const CLI_VERSION = _PKG.version;
const ISSUES_BASE = (_PKG.bugs && _PKG.bugs.url) || 'https://github.com/raccioly/docguard/issues';

// Keep the prefilled URL comfortably under GitHub's ~8 KB request-URL limit.
const URL_CAP = 1800;

/** Deterministic short id from a string — avoids Date.now()/Math.random(). */
function shortId(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = ((h << 5) + h + str.charCodeAt(i)) >>> 0;
  return h.toString(36).slice(0, 6);
}

/** Shared output deliberately excludes every source-derived string. */
export function buildIssueUrl(finding) {
  const code = Object.hasOwn(CODES, finding.code || '') ? finding.code : 'FINDING';
  const validator = CODES[code]?.validator || 'unknown';
  const title = `[feedback] ${code} (${validator}): detection feedback`;
  const confidence = ['high', 'medium', 'low'].includes(finding.confidence) ? finding.confidence : 'unknown';
  const body = [
    `DocGuard v${CLI_VERSION}`,
    `- Code: ${code}`,
    `- Validator: ${validator}`,
    `- Confidence: ${confidence}`,
    '',
    'Expected behavior:',
    'Actual behavior:',
    'Minimal synthetic reproduction (review before attaching):',
    '',
    'Check existing open AND closed issues and pull requests before submitting.',
    'A regression-test-only contribution is welcome; explain the expected behavior.',
    '',
    'Generated by docguard feedback. No project paths, messages, source code, or secret values are included.',
  ].join('\n');
  const url = `${ISSUES_BASE}/new?labels=docguard-feedback&title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;
  const query = `repo:raccioly/docguard ${code}`;
  const searchUrl = `https://github.com/search?q=${encodeURIComponent(query)}&type=issues`;
  return { url: url.length <= URL_CAP ? url : `${ISSUES_BASE}/new`, title, searchUrl };
}

export function runFeedback(projectDir, config, flags) {
  const data = runGuardInternal(projectDir, config);
  const selectedCode = typeof flags.code === 'string' ? flags.code.toUpperCase() : null;
  if (flags.code !== undefined && (!selectedCode || !Object.hasOwn(CODES, selectedCode))) {
    const error = 'Unknown finding code. Run docguard explain <CODE> to inspect supported findings.';
    if (flags.format === 'json') console.log(JSON.stringify({ error, reportable: [] }));
    else console.error(error);
    process.exitCode = 1;
    return;
  }
  const reportable = (data.findings || []).filter(f => selectedCode ? f.code === selectedCode : flags.all || f.reportable);
  const isJson = flags.format === 'json';

  if (reportable.length === 0) {
    if (isJson) {
      console.log(JSON.stringify({ reportable: [], message: 'no matching findings; use --code <CODE> or --all to challenge confident findings' }, null, 2));
      return;
    }
    console.log(`${c.bold}📮 DocGuard Feedback${c.reset}`);
    console.log(`${c.green}✅ No findings matched this selection. Confidence is not proof of correctness.${c.reset}`);
    console.log(`${c.dim}   Use --code <CODE> or --all to challenge a confident finding; --preview avoids saving records.${c.reset}\n`);
    return;
  }

  // Capture each reportable finding locally (full, reviewable) + build its URL.
  const feedbackDir = resolve(projectDir, '.docguard', 'feedback');
  const items = reportable.map((f) => {
    const id = shortId(`${f.code}|${f.location || f.message}`);
    const { url, title, searchUrl } = buildIssueUrl(f);
    const fileName = `${(f.code || 'finding').toLowerCase()}-${id}.json`;
    const filePath = resolve(feedbackDir, fileName);
    return { finding: f, id, url, title, searchUrl, fileName, filePath, saved: false, error: null };
  });

  let wrote = 0;
  for (const it of flags.preview ? [] : items) {
    try {
      if (!existsSync(feedbackDir)) mkdirSync(feedbackDir, { recursive: true });
      safeWrite(it.filePath, JSON.stringify({
        capturedBy: `docguard feedback (v${CLI_VERSION})`,
        finding: it.finding,
        issueUrl: it.url,
        searchUrl: it.searchUrl,
        sharing: 'The finding record can contain private project information. Share only a reviewed synthetic reproduction.',
      }, null, 2) + '\n');
      it.saved = true;
      wrote++;
    } catch (err) {
      it.error = `Unable to save feedback record (${err.code || 'write failed'}).`;
    }
  }

  if (items.some(it => it.error)) process.exitCode = 1;

  if (isJson) {
    console.log(JSON.stringify({
      version: CLI_VERSION,
      preview: Boolean(flags.preview),
      reportable: items.map(it => ({
        code: it.finding.code,
        location: it.finding.location,
        url: it.url,
        searchUrl: it.searchUrl,
        file: it.saved ? `.docguard/feedback/${it.fileName}` : null,
        saved: it.saved,
        error: it.error,
      })),
    }, null, 2));
    return;
  }

  console.log(`${c.bold}📮 DocGuard Feedback${c.reset}`);
  console.log(`${c.dim}   ${items.length} selected finding(s). ${flags.preview ? 'Preview only; no feedback records saved.' : `${wrote} local record(s) saved to .docguard/feedback/`}\n`);

  for (const it of items) {
    const f = it.finding;
    console.log(`  ${c.yellow}[${f.code}]${c.reset} ${f.message}`);
    if (f.suggestion && f.suggestion.pragma) {
      console.log(`     ${c.dim}Suppress locally instead: ${f.suggestion.pragma}${c.reset}`);
    }
    console.log(`     ${c.dim}Check for duplicates (including closed work): ${it.searchUrl}${c.reset}`);
    console.log(`     ${c.dim}Report (review before submitting):${c.reset}`);
    console.log(`     ${c.cyan}${it.url}${c.reset}`);
    if (it.saved) console.log(`     ${c.dim}Local copy (may contain private project details): .docguard/feedback/${it.fileName}${c.reset}\n`);
    if (it.error) console.error(`     ${c.red}${it.error}${c.reset}`);
  }

  console.log(`${c.dim}These reports help DocGuard stop flagging the same false positive in a future release.${c.reset}`);
  console.log(`${c.dim}Nothing is sent automatically — open a link only if you want to.${c.reset}\n`);
}
