/**
 * Feedback Command — close the loop with the tool's maintainers (v0.27).
 *
 * DocGuard is a tool for LLMs: when it gets something wrong, the cheapest way to
 * make the NEXT release better is to capture that signal. This command turns the
 * low-confidence findings of a guard run (candidate false positives — and any
 * other finding DocGuard itself flagged as uncertain) into:
 *
 *   1. a LOCAL-FIRST record under .docguard/feedback/<code>-<id>.json (full,
 *      reviewable, never sent anywhere automatically), and
 *   2. a one-click, PREFILLED GitHub issue URL that needs zero typing.
 *
 * Hard constraints (learned the hard way — see commit 3b600fd, where an
 * oversized prefilled URL overflowed GitHub's ~8 KB limit and silently failed):
 *   - The URL is CAPPED well under the limit; bulk lives in the local file.
 *   - It is REDACTED: no source code, no secret values — only a basename, a line
 *     number, and the safe `redactedContext` the validator built.
 *   - It is OPT-IN: nothing is filed automatically; the human clicks (or not).
 *
 * Not read-only in the strict sense — it writes its own .docguard/feedback/ —
 * but it never scaffolds skills and never touches the user's source tree.
 *
 * Zero npm dependencies — pure Node.js built-ins.
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { c } from '../shared.mjs';
import { runGuardInternal } from './guard.mjs';

const _PKG = JSON.parse(
  readFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', 'package.json'), 'utf-8')
);
const CLI_VERSION = _PKG.version;
const ISSUES_BASE = (_PKG.bugs && _PKG.bugs.url) || 'https://github.com/raccioly/docguard/issues';

// Keep the prefilled URL comfortably under GitHub's ~8 KB request-URL limit.
const URL_CAP = 1800;

/** Deterministic short id from a string — avoids Date.now()/Math.random(). */
function shortId(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = ((h << 5) + h + str.charCodeAt(i)) >>> 0;
  return h.toString(36).slice(0, 6);
}

/** Redact a finding location for the SHARED url: basename + line only. */
function safeLocation(location) {
  if (!location) return '(unknown)';
  const [path, line] = String(location).split(/:(?=\d+$)/);
  return line ? `${basename(path)}:${line}` : basename(path);
}

/**
 * Build a prefilled, capped issue URL. Drops optional body lines (longest-value
 * first) until under the cap; title + code + location always survive.
 */
function buildIssueUrl(finding) {
  const code = finding.code || 'FINDING';
  const validator = finding.validator || 'unknown';
  const shortMsg = (finding.message || '').replace(/\s+/g, ' ').slice(0, 70);
  const title = `[feedback] ${code} (${validator}): ${shortMsg}`;

  // Optional lines are ordered most→least droppable.
  const required = [
    `DocGuard v${CLI_VERSION} flagged this and it may be a false positive (or other feedback).`,
    '',
    `- Code: ${code}`,
    `- Validator: ${validator}`,
    `- Location: ${safeLocation(finding.location)}`,
    `- Confidence: ${finding.confidence}`,
  ];
  const optional = [];
  if (finding.redactedContext) optional.push(`- Context: ${finding.redactedContext}`);
  if (finding.suggestion && finding.suggestion.text) optional.push(`- Suggestion shown: ${finding.suggestion.text}`);
  const footer = ['', 'Generated by `docguard feedback` — no source code or secret values are included.'];

  const compose = (opt) => `${ISSUES_BASE}/new?labels=${encodeURIComponent('docguard-feedback')}` +
    `&title=${encodeURIComponent(title)}` +
    `&body=${encodeURIComponent([...required, ...opt, ...footer].join('\n'))}`;

  let opt = [...optional];
  let url = compose(opt);
  while (url.length > URL_CAP && opt.length > 0) {
    opt = opt.slice(0, -1);
    url = compose(opt);
  }
  if (url.length > URL_CAP) {
    // Even the required body is too long (pathological) — collapse to a stub.
    url = `${ISSUES_BASE}/new?labels=${encodeURIComponent('docguard-feedback')}` +
      `&title=${encodeURIComponent(title)}` +
      `&body=${encodeURIComponent(`DocGuard v${CLI_VERSION} — ${code} (${validator}). Full details saved locally; please attach.`)}`;
  }
  return { url, title };
}

export function runFeedback(projectDir, config, flags) {
  const data = runGuardInternal(projectDir, config);
  const reportable = (data.findings || []).filter((f) => f.reportable);
  const isJson = flags.format === 'json';

  if (reportable.length === 0) {
    if (isJson) {
      console.log(JSON.stringify({ reportable: [], message: 'no uncertain findings' }, null, 2));
      return;
    }
    console.log(`${c.bold}📮 DocGuard Feedback${c.reset}`);
    console.log(`${c.green}✅ Nothing to report — DocGuard is confident about everything it flagged.${c.reset}`);
    console.log(`${c.dim}   (Feedback collects low-confidence findings, i.e. likely false positives.)${c.reset}\n`);
    return;
  }

  // Capture each reportable finding locally (full, reviewable) + build its URL.
  const feedbackDir = resolve(projectDir, '.docguard', 'feedback');
  const items = reportable.map((f) => {
    const id = shortId(`${f.code}|${f.location || f.message}`);
    const { url, title } = buildIssueUrl(f);
    const fileName = `${(f.code || 'finding').toLowerCase()}-${id}.json`;
    const filePath = resolve(feedbackDir, fileName);
    return { finding: f, id, url, title, fileName, filePath };
  });

  if (isJson) {
    console.log(JSON.stringify({
      version: CLI_VERSION,
      reportable: items.map((it) => ({ code: it.finding.code, location: it.finding.location, url: it.url, file: `.docguard/feedback/${it.fileName}` })),
    }, null, 2));
    // Still write the local records so the JSON path is not a dead end.
  }

  let wrote = 0;
  for (const it of items) {
    try {
      if (!existsSync(feedbackDir)) mkdirSync(feedbackDir, { recursive: true });
      writeFileSync(it.filePath, JSON.stringify({
        capturedBy: `docguard feedback (v${CLI_VERSION})`,
        finding: it.finding,
        issueUrl: it.url,
      }, null, 2) + '\n', 'utf-8');
      wrote++;
    } catch { /* best-effort local capture */ }
  }

  if (isJson) return;

  console.log(`${c.bold}📮 DocGuard Feedback${c.reset}`);
  console.log(`${c.dim}   ${items.length} uncertain finding(s) — likely false positives. Saved locally to ${c.cyan}.docguard/feedback/${c.reset}\n`);

  for (const it of items) {
    const f = it.finding;
    console.log(`  ${c.yellow}[${f.code}]${c.reset} ${f.message}`);
    if (f.suggestion && f.suggestion.pragma) {
      console.log(`     ${c.dim}Suppress locally instead: ${f.suggestion.pragma}${c.reset}`);
    }
    console.log(`     ${c.dim}Report (1 click, prefilled, redacted):${c.reset}`);
    console.log(`     ${c.cyan}${it.url}${c.reset}`);
    console.log(`     ${c.dim}Local copy: .docguard/feedback/${it.fileName}${c.reset}\n`);
  }

  console.log(`${c.dim}These reports help DocGuard stop flagging the same false positive in a future release.${c.reset}`);
  console.log(`${c.dim}Nothing is sent automatically — open a link only if you want to.${c.reset}\n`);
}
