/**
 * llms Command — Generate llms.txt from canonical documentation
 *
 * llms.txt is a proposed standard (Jeremy Howard, Answer.AI, 2024) for providing
 * AI-friendly content summaries at a project root. This command generates it
 * from existing canonical docs.
 *
 * Usage:
 *   docguard llms                 — Generate/regenerate llms.txt
 *   docguard llms --stdout        — Print to stdout instead of file
 *
 * Integration:
 *   - `docguard init` includes llms.txt in standard template
 *   - `docguard generate` auto-regenerates llms.txt
 *   - `docguard guard` validates llms.txt exists and is current
 */

import { existsSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, join, basename } from 'node:path';
import { c } from '../shared.mjs';

// ──── Doc descriptions for llms.txt ────
const DOC_DESCRIPTIONS = {
  'ARCHITECTURE.md': 'System architecture, component boundaries, and tech stack',
  'DATA-MODEL.md': 'Database schemas, entity relationships, and data flow',
  'SECURITY.md': 'Authentication, authorization, secrets management, and security policies',
  'TEST-SPEC.md': 'Test coverage requirements, testing strategy, and quality rules',
  'ENVIRONMENT.md': 'Setup instructions, environment variables, and prerequisites',
  'API-REFERENCE.md': 'API endpoints, request/response formats, and integration docs',
  'DEPLOYMENT.md': 'Deployment procedures, CI/CD pipelines, and infrastructure',
  'MONITORING.md': 'Observability, logging, alerting, and health checks',
  'PERFORMANCE.md': 'Performance requirements, benchmarks, and optimization',
  'ACCESSIBILITY.md': 'WCAG compliance, accessibility standards, and testing',
};

const OPTIONAL_DOCS = {
  'DRIFT-LOG.md': 'Known deviations from canonical documentation',
  'CHANGELOG.md': 'Version history and release notes',
  'ROADMAP.md': 'Planned features and development roadmap',
  'REQUIREMENTS.md': 'Tracked requirements with traceability IDs',
  'AGENTS.md': 'AI agent behavior rules and workflow instructions',
  'CURRENT-STATE.md': 'Current implementation status and known issues',
};

/**
 * Generate llms.txt content from project docs.
 */
export function generateLlmsTxt(projectDir, config) {
  const lines = [];

  // ── Header ──
  const projectName = config.projectName || basename(projectDir);
  const description = getProjectDescription(projectDir);

  lines.push(`# ${projectName}`);
  if (description) {
    lines.push(`> ${description}`);
  }
  lines.push('');

  // ── Canonical Docs ──
  const docsDir = resolve(projectDir, 'docs-canonical');
  const existingDocs = [];

  if (existsSync(docsDir)) {
    try {
      const entries = readdirSync(docsDir).filter(f => f.endsWith('.md')).sort();
      for (const entry of entries) {
        const desc = DOC_DESCRIPTIONS[entry] || `${entry.replace('.md', '')} documentation`;
        existingDocs.push({ path: `docs-canonical/${entry}`, name: entry, desc });
      }
    } catch { /* ignore */ }
  }

  if (existingDocs.length > 0) {
    lines.push('## Docs');
    lines.push('');
    for (const doc of existingDocs) {
      lines.push(`- [${doc.name.replace('.md', '')}](${doc.path}): ${doc.desc}`);
    }
    lines.push('');
  }

  // ── Optional Docs ──
  const optionalFound = [];
  for (const [file, desc] of Object.entries(OPTIONAL_DOCS)) {
    if (existsSync(resolve(projectDir, file))) {
      optionalFound.push({ path: file, name: file, desc });
    }
  }

  if (optionalFound.length > 0) {
    lines.push('## Optional');
    lines.push('');
    for (const doc of optionalFound) {
      lines.push(`- [${doc.name.replace('.md', '')}](${doc.path}): ${doc.desc}`);
    }
    lines.push('');
  }

  // ── Footer ──
  lines.push('---');
  lines.push(`Generated by DocGuard v${config.version || 'unknown'} | [docguard-cli](https://www.npmjs.com/package/docguard-cli)`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Get project description from package.json or ARCHITECTURE.md.
 */
function getProjectDescription(projectDir) {
  // Try package.json first
  const pkgPath = resolve(projectDir, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
      if (pkg.description) return pkg.description;
    } catch { /* ignore */ }
  }

  // Try ARCHITECTURE.md first line after the header
  const archPath = resolve(projectDir, 'docs-canonical', 'ARCHITECTURE.md');
  if (existsSync(archPath)) {
    try {
      const content = readFileSync(archPath, 'utf-8');
      const lines = content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('|') && !trimmed.startsWith('-')) {
          return trimmed.substring(0, 200);
        }
      }
    } catch { /* ignore */ }
  }

  return null;
}

// llms-full.txt (v0.29): the Mintlify-popularized companion form — full doc
// bodies inlined, so an AI consumer gets everything in one fetch instead of
// chasing the llms.txt link index. Any single doc is capped to keep one
// runaway file from consuming the whole context window.
const FULL_DOC_LINE_CAP = 400;

/**
 * Generate llms-full.txt content — llms.txt header + inlined doc bodies.
 */
export function generateLlmsFullTxt(projectDir, config) {
  const lines = [];
  const projectName = config.projectName || basename(projectDir);
  const description = getProjectDescription(projectDir);

  lines.push(`# ${projectName}`);
  if (description) lines.push(`> ${description}`);
  lines.push('');
  lines.push('<!-- llms-full.txt — full-content form. The link-index form is llms.txt. -->');
  lines.push('<!-- Generated by DocGuard (docguard llms --full). Regenerate after doc changes. -->');
  lines.push('');

  // Same doc discovery as the index form: canonical docs + present optional docs.
  const docPaths = [];
  const docsDir = resolve(projectDir, 'docs-canonical');
  if (existsSync(docsDir)) {
    try {
      for (const entry of readdirSync(docsDir).filter(f => f.endsWith('.md')).sort()) {
        docPaths.push({ path: `docs-canonical/${entry}`, desc: DOC_DESCRIPTIONS[entry] || null });
      }
    } catch { /* ignore */ }
  }
  for (const [file, desc] of Object.entries(OPTIONAL_DOCS)) {
    if (existsSync(resolve(projectDir, file))) docPaths.push({ path: file, desc });
  }

  for (const { path, desc } of docPaths) {
    let content;
    try { content = readFileSync(resolve(projectDir, path), 'utf-8'); } catch { continue; }
    lines.push('---');
    lines.push('');
    lines.push(`## ${path}`);
    if (desc) lines.push(`> ${desc}`);
    lines.push('');
    const docLines = content.split('\n');
    if (docLines.length > FULL_DOC_LINE_CAP) {
      lines.push(...docLines.slice(0, FULL_DOC_LINE_CAP));
      lines.push('');
      lines.push(`<!-- truncated: ${docLines.length - FULL_DOC_LINE_CAP} more lines — read ${path} directly -->`);
    } else {
      lines.push(...docLines);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by DocGuard | [docguard-cli](https://www.npmjs.com/package/docguard-cli)`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Public command — generate llms.txt (or llms-full.txt with --full).
 */
export function runLlms(projectDir, config, flags) {
  const full = !!flags.full;
  const content = full ? generateLlmsFullTxt(projectDir, config) : generateLlmsTxt(projectDir, config);

  if (flags.stdout) {
    console.log(content);
    return;
  }

  const fileName = full ? 'llms-full.txt' : 'llms.txt';
  const outputPath = resolve(projectDir, fileName);
  writeFileSync(outputPath, content, 'utf-8');

  console.log(`${c.bold}📄 DocGuard ${fileName} Generator${c.reset}`);
  console.log(`${c.green}✅ Generated ${outputPath}${c.reset}`);
  console.log(`${c.dim}   Standard: llms.txt (Jeremy Howard, Answer.AI, 2024)${full ? ' — full-content form' : ''}${c.reset}`);
  console.log(`${c.dim}   DocGuard keeps this in sync with your canonical docs.${c.reset}`);
  console.log('');
}
