/**
 * llms Command — Generate llms.txt from canonical documentation
 *
 * llms.txt is a proposed standard (Jeremy Howard, Answer.AI, 2024) for providing
 * AI-friendly content summaries at a project root. This command generates it
 * from existing canonical docs.
 *
 * Usage:
 *   docguard llms                 — Generate/regenerate llms.txt
 *   docguard llms --stdout        — Print to stdout instead of file
 *
 * Integration:
 *   - `docguard init` includes llms.txt in standard template
 *   - `docguard generate` auto-regenerates llms.txt
 *   - `docguard guard` validates llms.txt exists and is current
 */

import { existsSync, readFileSync } from 'node:fs';
import { resolve, join, basename } from 'node:path';
import { c, TOOL_VERSION } from '../shared.mjs';
import { listCanonicalDocs } from '../shared-ignore.mjs';
import { safeWrite } from '../writers/generate-io.mjs';

// ──── Doc descriptions for llms.txt ────
const DOC_DESCRIPTIONS = {
  'ARCHITECTURE.md': 'System architecture, component boundaries, and tech stack',
  'DATA-MODEL.md': 'Database schemas, entity relationships, and data flow',
  'SECURITY.md': 'Authentication, authorization, secrets management, and security policies',
  'TEST-SPEC.md': 'Test coverage requirements, testing strategy, and quality rules',
  'ENVIRONMENT.md': 'Setup instructions, environment variables, and prerequisites',
  'API-REFERENCE.md': 'API endpoints, request/response formats, and integration docs',
  'DEPLOYMENT.md': 'Deployment procedures, CI/CD pipelines, and infrastructure',
  'MONITORING.md': 'Observability, logging, alerting, and health checks',
  'PERFORMANCE.md': 'Performance requirements, benchmarks, and optimization',
  'ACCESSIBILITY.md': 'WCAG compliance, accessibility standards, and testing',
};

const OPTIONAL_DOCS = {
  'DRIFT-LOG.md': 'Known deviations from canonical documentation',
  'CHANGELOG.md': 'Version history and release notes',
  'ROADMAP.md': 'Planned features and development roadmap',
  'REQUIREMENTS.md': 'Tracked requirements with traceability IDs',
  'AGENTS.md': 'AI agent behavior rules and workflow instructions',
  'CURRENT-STATE.md': 'Current implementation status and known issues',
};

/**
 * The exact doc set both llms forms cover, in emission order: every canonical
 * doc (recursive — a nested doc still belongs in the bundle), then the optional
 * root docs that are actually present.
 *
 * Exported because the two forms MUST agree on this set. They render it
 * differently — the index form falls back to a derived description, the full
 * form omits the line when there is none — so `description` is the raw lookup
 * and each caller applies its own policy.
 *
 * @returns {{path: string, name: string, description: string|null, canonical: boolean}[]}
 */
export function llmsDocSet(projectDir) {
  const docs = [];
  for (const doc of listCanonicalDocs(projectDir)) {
    const name = basename(doc.rel);
    docs.push({ path: doc.rel, name, description: DOC_DESCRIPTIONS[name] || null, canonical: true });
  }
  for (const [file, description] of Object.entries(OPTIONAL_DOCS)) {
    if (existsSync(resolve(projectDir, file))) {
      docs.push({ path: file, name: file, description, canonical: false });
    }
  }
  return docs;
}

/**
 * Generate llms.txt content from project docs.
 */
export function generateLlmsTxt(projectDir, config) {
  const lines = [];

  // ── Header ──
  const projectName = config.projectName || basename(projectDir);
  const description = getProjectDescription(projectDir);

  lines.push(`# ${projectName}`);
  if (description) {
    lines.push(`> ${description}`);
  }
  lines.push('');

  // ── Canonical Docs ── (recursive — a nested doc still belongs in llms.txt)
  const docSet = llmsDocSet(projectDir);
  const existingDocs = docSet
    .filter(d => d.canonical)
    .map(d => ({
      path: d.path,
      name: d.name,
      // The index form always carries a description; derive one when the doc
      // is not in the curated table.
      desc: d.description || `${d.name.replace('.md', '')} documentation`,
    }));

  if (existingDocs.length > 0) {
    lines.push('## Docs');
    lines.push('');
    for (const doc of existingDocs) {
      lines.push(`- [${doc.name.replace('.md', '')}](${doc.path}): ${doc.desc}`);
    }
    lines.push('');
  }

  // ── Optional Docs ──
  const optionalFound = docSet
    .filter(d => !d.canonical)
    .map(d => ({ path: d.path, name: d.name, desc: d.description }));

  if (optionalFound.length > 0) {
    lines.push('## Optional');
    lines.push('');
    for (const doc of optionalFound) {
      lines.push(`- [${doc.name.replace('.md', '')}](${doc.path}): ${doc.desc}`);
    }
    lines.push('');
  }

  // ── Footer ──
  lines.push('---');
  // TOOL_VERSION, never config.version: the latter is the .docguard.json SCHEMA
  // version, so this footer used to tell every adopter DocGuard was "v0.6".
  lines.push(`Generated by DocGuard v${TOOL_VERSION} | [docguard-cli](https://www.npmjs.com/package/docguard-cli)`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Get project description from package.json or ARCHITECTURE.md.
 */
function getProjectDescription(projectDir) {
  // Try package.json first
  const pkgPath = resolve(projectDir, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
      if (pkg.description) return pkg.description;
    } catch { /* ignore */ }
  }

  // Try ARCHITECTURE.md first line after the header
  const archPath = resolve(projectDir, 'docs-canonical', 'ARCHITECTURE.md');
  if (existsSync(archPath)) {
    try {
      const content = readFileSync(archPath, 'utf-8');
      const lines = content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('|') && !trimmed.startsWith('-')) {
          return trimmed.substring(0, 200);
        }
      }
    } catch { /* ignore */ }
  }

  return null;
}

// llms-full.txt (v0.29): the Mintlify-popularized companion form — full doc
// bodies inlined, so an AI consumer gets everything in one fetch instead of
// chasing the llms.txt link index. Any single doc is capped to keep one
// runaway file from consuming the whole context window.
const FULL_DOC_LINE_CAP = 400;

/**
 * Generate llms-full.txt content — llms.txt header + inlined doc bodies.
 */
export function generateLlmsFullTxt(projectDir, config) {
  const lines = [];
  const projectName = config.projectName || basename(projectDir);
  const description = getProjectDescription(projectDir);

  lines.push(`# ${projectName}`);
  if (description) lines.push(`> ${description}`);
  lines.push('');
  lines.push('<!-- llms-full.txt — full-content form. The link-index form is llms.txt. -->');
  lines.push('<!-- Generated by DocGuard (docguard llms --full). Regenerate after doc changes. -->');
  lines.push('');

  // Same doc discovery as the index form — literally the same function, so the
  // two forms cannot drift apart on which docs they cover.
  for (const { path, description: desc } of llmsDocSet(projectDir)) {
    let content;
    try { content = readFileSync(resolve(projectDir, path), 'utf-8'); } catch { continue; }
    lines.push('---');
    lines.push('');
    lines.push(`## ${path}`);
    if (desc) lines.push(`> ${desc}`);
    lines.push('');
    const docLines = content.split('\n');
    if (docLines.length > FULL_DOC_LINE_CAP) {
      lines.push(...docLines.slice(0, FULL_DOC_LINE_CAP));
      lines.push('');
      lines.push(`<!-- truncated: ${docLines.length - FULL_DOC_LINE_CAP} more lines — read ${path} directly -->`);
    } else {
      lines.push(...docLines);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by DocGuard v${TOOL_VERSION} | [docguard-cli](https://www.npmjs.com/package/docguard-cli)`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Public command — generate llms.txt (or llms-full.txt with --full).
 */
export function runLlms(projectDir, config, flags) {
  const full = !!flags.full;
  const content = full ? generateLlmsFullTxt(projectDir, config) : generateLlmsTxt(projectDir, config);

  if (flags.stdout) {
    console.log(content);
    return;
  }

  const fileName = full ? 'llms-full.txt' : 'llms.txt';
  const outputPath = resolve(projectDir, fileName);
  safeWrite(outputPath, content);

  console.log(`${c.bold}📄 DocGuard ${fileName} Generator${c.reset}`);
  console.log(`${c.green}✅ Generated ${outputPath}${c.reset}`);
  console.log(`${c.dim}   Standard: llms.txt (Jeremy Howard, Answer.AI, 2024)${full ? ' — full-content form' : ''}${c.reset}`);
  console.log(`${c.dim}   DocGuard keeps this in sync with your canonical docs.${c.reset}`);
  console.log('');
}
