/**
 * Memory Command — v0.17-P2.
 *
 * `docguard memory` shows the documentation-memory accuracy headline that
 * already appears in `docguard score`, but adds a `--diff` mode that drills
 * into WHICH claims don't match code. Reported by a Python user:
 *
 *   "Memory accuracy 83% with no drill-down. The headline number was the
 *    only signal — there's no `docguard memory --diff` to show which doc
 *    claim doesn't match the code."
 *
 * The numbers are the same ones `score` shows; this command's value is
 * making them inspectable per-domain.
 *
 * Domains drilled into:
 *   - Endpoints: API-REFERENCE.md vs scanned routes
 *   - Entities:  DATA-MODEL.md vs scanned schemas
 *   - Env vars:  ENVIRONMENT.md vs process.env / import.meta.env usage
 *   - Tech:      ARCHITECTURE.md vs detected stack
 *
 * Zero NPM dependencies. Pure orchestration of existing diff helpers.
 */

import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { c } from '../shared.mjs';
import { diffRoutes, diffEntities, diffEnvVars, diffTechStack } from './diff.mjs';
import { buildMemoryPlan } from '../scanners/memory-plan.mjs';
import { runGuardInternal } from './guard.mjs';

/**
 * Compute an accuracy score for a single domain. Returns:
 *   { matched, total, accuracy: 0..100, onlyInDocs, onlyInCode }
 * `null` when the domain isn't applicable (e.g. no API-REFERENCE.md).
 */
function _domainAccuracy(d) {
  if (!d) return null;
  const matched = (d.matched || []).length;
  const onlyDocs = (d.onlyInDocs || []).length;
  const onlyCode = (d.onlyInCode || []).length;
  const total = matched + onlyDocs + onlyCode;
  if (total === 0) return null;
  return {
    title: d.title,
    icon: d.icon,
    matched,
    onlyInDocs: d.onlyInDocs || [],
    onlyInCode: d.onlyInCode || [],
    total,
    accuracy: Math.round((matched / total) * 100),
  };
}

// ── Context pack (v0.29) ─────────────────────────────────────────────────────

/** H2 sections of AGENTS.md whose heading reads like rules/conventions/workflow. */
function extractConventions(agentsMd, capLines = 60) {
  const out = [];
  const lines = agentsMd.split('\n');
  let taking = false;
  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+)$/);
    if (h2) taking = /rules|conventions|workflow/i.test(h2[1]);
    if (taking) {
      out.push(line);
      if (out.length >= capLines) {
        out.push('<!-- truncated — read AGENTS.md for the full rules -->');
        break;
      }
    }
  }
  return out;
}

/**
 * `docguard memory --pack` — write .docguard/context-pack.md: a compact,
 * code-truth-stamped session-start context for an AI agent. Everything in it
 * is derived from scanners (buildMemoryPlan) and guard — numbers, not prose —
 * so it can't hallucinate and is always regenerable.
 */
function runMemoryPack(projectDir, config, flags) {
  const plan = buildMemoryPlan(projectDir, config);
  const guard = runGuardInternal(projectDir, config);
  const lines = [];

  lines.push(`# Context Pack — ${config.projectName}`);
  lines.push('');
  lines.push(`<!-- Generated by \`docguard memory --pack\` ${new Date().toISOString()} — regenerate, don't edit -->`);
  lines.push('');
  lines.push(`**Guard:** ${guard.status} — ${guard.passed}/${guard.total} checks (${guard.errors} error(s), ${guard.warnings} warning(s))`);
  lines.push('');

  lines.push('## Code-truth surface');
  lines.push('');
  lines.push(`- Stack: ${plan.profile.languages.join(', ') || 'unknown'}${plan.profile.frameworks.length ? ` · ${plan.profile.frameworks.join(', ')}` : ''} · kind: ${plan.profile.kind}`);
  lines.push(`- Modules: ${plan.surface.modules.length} · Endpoints: ${plan.surface.endpoints.length} · Entities: ${plan.surface.entities.length} · Env vars: ${plan.surface.envVars.length}`);
  lines.push(`- Tests: ${plan.surface.tests.totalFiles} files, ${plan.surface.tests.totalCases} cases`);
  lines.push('');

  const docsDir = resolve(projectDir, 'docs-canonical');
  if (existsSync(docsDir)) {
    lines.push('## Canonical docs');
    lines.push('');
    let entries = [];
    try { entries = readdirSync(docsDir).filter(f => f.endsWith('.md')).sort(); } catch { /* ignore */ }
    for (const doc of entries) {
      let reviewed = '';
      try {
        const m = readFileSync(resolve(docsDir, doc), 'utf-8').match(/docguard:last-reviewed\s+(\d{4}-\d{2}-\d{2})/);
        if (m) reviewed = ` (last-reviewed ${m[1]})`;
      } catch { /* ignore */ }
      lines.push(`- docs-canonical/${doc}${reviewed}`);
    }
    lines.push('');
  }

  const agentsPath = resolve(projectDir, 'AGENTS.md');
  if (existsSync(agentsPath)) {
    let conventions = [];
    try { conventions = extractConventions(readFileSync(agentsPath, 'utf-8')); } catch { /* ignore */ }
    if (conventions.length > 0) {
      lines.push('## Project rules (from AGENTS.md)');
      lines.push('');
      lines.push(...conventions);
      lines.push('');
    }
  }

  const driftPath = resolve(projectDir, 'DRIFT-LOG.md');
  if (existsSync(driftPath)) {
    try {
      const drift = readFileSync(driftPath, 'utf-8');
      const entries = drift.match(/^##\s+.+$/gm) || [];
      if (entries.length > 0) {
        lines.push('## Known drift');
        lines.push('');
        lines.push(`- ${entries.length} logged deviation(s); latest: ${entries[entries.length - 1].replace(/^##\s+/, '')}`);
        lines.push('');
      }
    } catch { /* ignore */ }
  }

  lines.push('---');
  lines.push('Verify claims: `docguard verify --semantic` · Full docs: `llms-full.txt`');
  lines.push('');
  const content = lines.join('\n');

  if (flags.stdout) {
    console.log(content);
    return;
  }
  const outDir = resolve(projectDir, '.docguard');
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, 'context-pack.md');
  writeFileSync(outPath, content, 'utf-8');
  console.log(`${c.bold}🧠 DocGuard Context Pack${c.reset}`);
  console.log(`${c.green}✅ Wrote ${outPath}${c.reset} ${c.dim}(${lines.length} lines — load at agent session start)${c.reset}`);
  console.log('');
}

export function runMemory(projectDir, config, flags) {
  // v0.29: --pack writes the agent context pack and exits — a separate output
  // artifact, not a display mode of the accuracy drill-down below.
  if (flags.pack) return runMemoryPack(projectDir, config, flags);

  const isJson = flags.format === 'json';
  const wantsDiff = flags.diff || (flags.args || []).includes('--diff');

  const domains = {
    endpoints: _domainAccuracy(diffRoutes(projectDir, config)),
    entities:  _domainAccuracy(diffEntities(projectDir, config)),
    envVars:   _domainAccuracy(diffEnvVars(projectDir, config)),
    techStack: _domainAccuracy(diffTechStack(projectDir, config)),
  };

  // Roll up across applicable domains.
  let totalMatched = 0;
  let totalChecks = 0;
  for (const d of Object.values(domains)) {
    if (!d) continue;
    totalMatched += d.matched;
    totalChecks += d.total;
  }
  const overallAccuracy = totalChecks > 0
    ? Math.round((totalMatched / totalChecks) * 100)
    : 0;

  if (isJson) {
    console.log(JSON.stringify({
      project: config.projectName,
      accuracy: overallAccuracy,
      domains,
      totals: { matched: totalMatched, checks: totalChecks },
      timestamp: new Date().toISOString(),
    }, null, 2));
    return;
  }

  // ── Text output ──
  console.log(`${c.bold}🧠 DocGuard Memory${c.reset} ${c.dim}— ${config.projectName}${c.reset}\n`);

  // Label is `Claim match rate` (not `Accuracy`) to disambiguate from the
  // score-level `Accuracy` metric in `docguard score`, which is a weighted
  // average across the entire accuracy axis (apiSurface, environment, drift,
  // metadata-sync, etc.) and uses a different denominator. Both numbers are
  // legitimate, but the same word was pointing at two different calculations
  // — users saw "Accuracy 0%" here and "Accuracy 93%" in `score` on the same
  // project and reasonably read it as a contradiction. This metric is the
  // strict per-claim ratio (matched claims / total checked claims, restricted
  // to domains that actually have any claims).
  const accColor = overallAccuracy >= 90 ? c.green : overallAccuracy >= 70 ? c.yellow : c.red;
  console.log(`  ${c.bold}Claim match rate:${c.reset} ${accColor}${overallAccuracy}%${c.reset} ${c.dim}(${totalMatched}/${totalChecks} doc claims match code)${c.reset}`);
  console.log(`  ${c.dim}   ↳ See ${c.cyan}docguard score${c.dim} for the weighted accuracy axis across all domains.${c.reset}\n`);

  if (totalChecks === 0) {
    console.log(`  ${c.dim}No applicable domains found — add canonical docs (API-REFERENCE.md, DATA-MODEL.md, ENVIRONMENT.md) and rerun.${c.reset}`);
    return;
  }

  // Per-domain breakdown
  console.log(`  ${c.bold}By domain:${c.reset}`);
  for (const [name, d] of Object.entries(domains)) {
    if (!d) continue;
    const domainColor = d.accuracy >= 90 ? c.green : d.accuracy >= 70 ? c.yellow : c.red;
    console.log(`     ${d.icon} ${c.cyan}${d.title.padEnd(22)}${c.reset} ${domainColor}${String(d.accuracy).padStart(3)}%${c.reset}  ${c.dim}${d.matched}/${d.total} matched${c.reset}`);
  }

  if (!wantsDiff) {
    if (overallAccuracy < 100) {
      console.log(`\n  ${c.dim}Run ${c.cyan}docguard memory --diff${c.dim} to see WHICH claims don't match.${c.reset}`);
    }
    return;
  }

  // --diff mode: detail per domain
  console.log(`\n  ${c.bold}── Drill-down ──${c.reset}`);
  let anyShown = false;
  for (const [_, d] of Object.entries(domains)) {
    if (!d) continue;
    if (d.onlyInDocs.length === 0 && d.onlyInCode.length === 0) continue;
    anyShown = true;
    console.log(`\n  ${d.icon} ${c.bold}${d.title}${c.reset} ${c.dim}(${d.accuracy}%)${c.reset}`);

    if (d.onlyInDocs.length > 0) {
      console.log(`     ${c.red}✗ In docs but missing from code${c.reset} ${c.dim}(${d.onlyInDocs.length}):${c.reset}`);
      for (const item of d.onlyInDocs.slice(0, 10)) {
        console.log(`         ${c.red}-${c.reset} ${item}`);
      }
      if (d.onlyInDocs.length > 10) console.log(`         ${c.dim}... ${d.onlyInDocs.length - 10} more${c.reset}`);
    }

    if (d.onlyInCode.length > 0) {
      console.log(`     ${c.yellow}⚠ In code but missing from docs${c.reset} ${c.dim}(${d.onlyInCode.length}):${c.reset}`);
      for (const item of d.onlyInCode.slice(0, 10)) {
        console.log(`         ${c.yellow}+${c.reset} ${item}`);
      }
      if (d.onlyInCode.length > 10) console.log(`         ${c.dim}... ${d.onlyInCode.length - 10} more${c.reset}`);
    }
  }

  if (!anyShown) {
    console.log(`\n  ${c.green}✅ All claims match — nothing to drill into.${c.reset}`);
  } else {
    console.log(`\n  ${c.dim}Fix options:${c.reset}`);
    console.log(`    ${c.dim}• Removed-from-code items: ${c.cyan}docguard fix --write${c.dim} (deletes documented-but-absent endpoints)${c.reset}`);
    console.log(`    ${c.dim}• Missing-from-docs items: ${c.cyan}/docguard.fix --doc <name>${c.dim} (AI fills in the gap)${c.reset}`);
  }
}
